# Generated by Django 5.1.6 on 2025-03-12 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_orders_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverypatern',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered')], default='pending', max_length=255),
        ),
    ]
